### PR TITLE
Change 'pybench' to 'pyperf'

### PR DESCRIPTION
**Pull request by Tinche**
A small docfix.

### CODE REVIEW

**Comment by haypo** [comment]
Merged, thanks.

**Comment by haypo** [comment]
Oh wait, I'm unable to merge this PR on my phone.

**Comment by Tinche** [comment]
Hm, there was an error (i.e. not a failure) on one of the Travis jobs. Can we get it to try again somehow?

**Comment by Tinche** [comment]
Hm googling around, people say a rebuild can be triggered by marking a pull request closed, then remarking it open, so I'm gonna try that.

**Comment by haypo** [comment]
Your trick worked. I merged your PR. Sorty for the CI issue, it's the first time that I get such failure.

**Pull request merged**
